### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by NicmeisteR** [fluxer/warmux#1]
Could you please help me figure out how to compile this project because I cant seem to get it to work.

**Comment by fluxer** [comment]
Sorry for the late reply,

It is possible to build the project with autotools or cmake. You will likely need the dependencies installed, altho they are common for games you may need to install the development packages first which depends on your operating system. Once you have those you can open up a terminal and execute one of the following:
```
git clone --depth 1 https://github.com/fluxer/warmux/
cd warmux
./autogen.sh
./configure --prefix=/usr
make
make install
```
or:
```
git clone --depth 1 https://github.com/fluxer/warmux/
cd warmux
cmake -DCMAKE_INSTALL_PREFIX=/usr
make
make install
```
I do not recommend installing in /usr prefix if you can find git package files and adjust them to use my repo instead because your operating system will not be aware of the game (package manager wise) and you may not be able to uinstall the game later in case you want to do that. If you are running Arch Linux for an example there is https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=warmux-git which you can change the source array of and use makepkg and pacman to install an actual package for Arch. However, if you do not install it with /usr prefix it is unlikely you will be able to run the game simply from your applications menu for several reasons.

I hope that helps
